# Generated by Django 4.1.3 on 2023-04-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workingspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urequest',
            name='response_date',
        ),
    ]
